title: "Sajan C Patel"
description: "Biomedical Engineering | Neural Engineering | Restoring Movement"
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

# metadata for SEO
author: "Your Name"